version: v2beta1
name: genie

pipelines:
  dev:
    run: |-
      run_dependencies --all       # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all    # 2. Ensure pull secrets
      create_deployments --all     # 3. Deploy Helm charts and manifests specfied as "deployments"
      start_dev genie                # 4. Start dev mode "genie" (see "dev" section)
  deploy:
    run: |-
      run_dependencies --all                            # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all                         # 2. Ensure pull secrets
      build_images --all -t $(git describe --always)    # 3. Build, tag (git commit hash) and push all images (see "images")
      create_deployments --all                          # 4. Deploy Helm charts and manifests specfied as "deployments"

images:
  genie:
    image: genie
    dockerfile: ./Dockerfile

deployments:
  genie:
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
          - image: genie
            volumeMounts:
              - containerPath: /etc/config
                volume:
                  name: watchpoints-vol
                  readonly: false
#            env:
#              - name: GLOBAL_CONFIG
#                valueFrom:
#                  configMapKeyRef:
#                    "name": "watchpoints"
#                    "key": "global"
        volumes:
          - name: watchpoints-vol
            configMap:
              name: watchpoints
        service:
          ports:
            - port: 8080
dev:
  genie:
    imageSelector: genie:${runtime.images.genie.tag}
    devImage: ghcr.io/loft-sh/devspace-containers/go:1.20-alpine
    sync:
      - path: ./
    terminal:
      command: ./devspace_start.sh
    ssh:
      enabled: true
    proxyCommands:
      - command: devspace
      - command: kubectl
      - command: helm
      - gitCredentials: true
    ports:
      - port: "2345"
      - port: "8080"
    open:
      - url: http://localhost:8080




#commands:
#  migrate-db:
#    command: |-
#      echo 'This is a cross-platform, shared command that can be used to codify any kind of dev task.'
#      echo 'Anyone using this project can invoke it via "devspace run migrate-db"'

